-- Tabela CELULA
CREATE TABLE CELULA (
    ID_CELULA INT PRIMARY KEY AUTO_INCREMENT,
    DSC_CEL VARCHAR(20) NOT NULL
);

-- Tabela VIDRO
CREATE TABLE VIDRO (
    ID_VIDRO INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_VIDRO VARCHAR(20) NOT NULL,
    ESPESSURA DECIMAL(2,1) NOT NULL
);

-- Tabela ESTRUTURA
CREATE TABLE ESTRUTURA (
    ID_ESTRUTURA INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO_ESTRUTURA VARCHAR(50) NOT NULL
);

-- Tabela CAIXA_CONEXAO
CREATE TABLE CAIXA_CONEXAO (
    ID_CAIXA_CONEXAO INT PRIMARY KEY AUTO_INCREMENT,
    IP INT NOT NULL,
    DID INT NOT NULL,
    ESPESSURA_CABO DECIMAL(2,1) NOT NULL,
    COMPRIMENTO DECIMAL(2,1) NOT NULL,
    TIPO_CONEXAO VARCHAR(20) NOT NULL
);

-- Tabela TAMANHO
CREATE TABLE TAMANHO (
    ID_TAMANHO INT PRIMARY KEY AUTO_INCREMENT,
    ALTURA INT NOT NULL,
    LARGURA INT NOT NULL,
    ESPESSURA DECIMAL(2,1) NOT NULL
);

-- Tabela PLACA
CREATE TABLE PLACA (
    ID_PLACA INT PRIMARY KEY AUTO_INCREMENT,
    PRECO DECIMAL(6,2) NOT NULL,
    POTENCIA_MAX INT NOT NULL,
    TENS_POTENCIA DECIMAL(4,2) NOT NULL,
    CORRENTE_POTENCIA DECIMAL(4,2) NOT NULL,
    TENS_CIRC DECIMAL(4,2) NOT NULL,
    CORRENTE_CURTO DECIMAL(4,2) NOT NULL,
    EFICIENCIA DECIMAL(5,2) NOT NULL,
    TOLERANCIA_POSITIVA INT NOT NULL,
    TEMP_MIN INT NOT NULL,
    TEMP_MAX INT NOT NULL,
    TEMP_MAX_SUPORTE INT NOT NULL,
    FUSIVEL INT NOT NULL,
    NUM_CELULAS INT NOT NULL,
    ID_CELULA INT NOT NULL,
    ID_VIDRO INT NOT NULL,
    ID_ESTRUTURA INT NOT NULL,
    ID_CAIXA_CONEXAO INT NOT NULL,
    ID_TAMANHO INT NOT NULL,
    PESO DECIMAL(5,1) NOT NULL,
    IMETRO VARCHAR(11),

    FOREIGN KEY (ID_CELULA) REFERENCES CELULA(ID_CELULA),
    FOREIGN KEY (ID_VIDRO) REFERENCES VIDRO(ID_VIDRO),
    FOREIGN KEY (ID_ESTRUTURA) REFERENCES ESTRUTURA(ID_ESTRUTURA),
    FOREIGN KEY (ID_CAIXA_CONEXAO) REFERENCES CAIXA_CONEXAO(ID_CAIXA_CONEXAO),
    FOREIGN KEY (ID_TAMANHO) REFERENCES TAMANHO(ID_TAMANHO)
);

-- Tabela ESTADO
CREATE TABLE ESTADO (
    ID_ESTADO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_ESTADO VARCHAR(50) NOT NULL,
    UF CHAR(2) NOT NULL UNIQUE
);

-- Tabela CIDADE
CREATE TABLE CIDADE (
    ID_CIDADE INT PRIMARY KEY AUTO_INCREMENT,
    NOME_CIDADE VARCHAR(100) NOT NULL,
    ID_ESTADO INT NOT NULL,
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
);

-- Tabela RUA
CREATE TABLE RUA (
    ID_RUA INT PRIMARY KEY AUTO_INCREMENT,
    NOME_RUA VARCHAR(150) NOT NULL,
    ID_CIDADE INT NOT NULL,
    FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID_CIDADE)
);

-- Tabela ENDERECO_BASE
CREATE TABLE ENDERECO_BASE (
    CEP VARCHAR(8) PRIMARY KEY,
    ID_RUA INT NOT NULL,
    ID_CIDADE INT NOT NULL,
    ID_ESTADO INT NOT NULL,
    FOREIGN KEY (ID_RUA) REFERENCES RUA(ID_RUA),
    FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID_CIDADE),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
);

-- Tabela CLIENTE (com IsAdmin)
CREATE TABLE CLIENTE (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    CPF_CNPJ VARCHAR(14) NOT NULL UNIQUE,
    NOME_CLIENTE VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    IsAdmin BOOLEAN DEFAULT FALSE
);

-- Tabela CLIENTE_ENDERECO
CREATE TABLE CLIENTE_ENDERECO (
    ID_CLIENTE_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    CEP VARCHAR(8) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    COMPLEMENTO VARCHAR(100),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    FOREIGN KEY (CEP) REFERENCES ENDERECO_BASE(CEP)
);

-- Tabela CONTA
CREATE TABLE CONTA (
    ID_CONTA INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA_HASH CHAR(200) NOT NULL,
    TELEFONE VARCHAR(15),
    DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    ULTIMO_LOGIN DATETIME,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

-- Tabela CONSUMO
CREATE TABLE CONSUMO (
    ID_CLIENTE INT NOT NULL,
    ANO INT NOT NULL CHECK (ANO BETWEEN 2000 AND 2100),
    MES INT NOT NULL CHECK (MES BETWEEN 1 AND 12),
    CONSUMO_KWH DECIMAL(6,2) NOT NULL CHECK (CONSUMO_KWH >= 0),
    VALOR_TOTAL DECIMAL(8,2) CHECK (VALOR_TOTAL >= 0),
    TIPO_CONSUMO ENUM('RESIDENCIAL', 'COMERCIAL', 'INDUSTRIAL') DEFAULT 'RESIDENCIAL',
    FONTE_ENERGIA ENUM('REDE', 'SOLAR', 'MISTA') DEFAULT 'REDE',
    OBSERVACOES VARCHAR(255),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

-- Índices recomendados
CREATE INDEX idx_consumo_cliente_data ON CONSUMO(ID_CLIENTE, ANO, MES);
CREATE INDEX idx_cliente_endereco ON CLIENTE_ENDERECO(ID_CLIENTE);
