delete tables
DROP TABLE INSTALACAO_PLACA CASCADE CONSTRAINTS;
DROP TABLE INSTALACAO CASCADE CONSTRAINTS;
DROP TABLE CLIENTE_ENDERECO CASCADE CONSTRAINTS;
DROP TABLE PLACA CASCADE CONSTRAINTS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE ENDERECO_BASE CASCADE CONSTRAINTS;
DROP TABLE RUA CASCADE CONSTRAINTS;
DROP TABLE CIDADE CASCADE CONSTRAINTS;
DROP TABLE ESTADO CASCADE CONSTRAINTS;
DROP TABLE CELULA CASCADE CONSTRAINTS;
DROP TABLE VIDRO CASCADE CONSTRAINTS;
DROP TABLE ESTRUTURA CASCADE CONSTRAINTS;
DROP TABLE CAIXA_CONEXAO CASCADE CONSTRAINTS;
DROP TABLE TAMANHO CASCADE CONSTRAINTS;
table placas
create table CELULA(
 ID_CELULA number(4) not null,
 DSC_CEL varchar2 (20) not null,
 primary key (ID_CELULA)
);
create table VIDRO(
 ID_VIDRO number(4) not null,
 TIP varchar2(20) not null,
 ESPE number(2,1) not null,
 primary key (ID_VIDRO)
);
create table ESTRUTURA(
 ID_ESTRUTURA number(4) not null,
 DES_ESTU varchar2(50) not null,
 primary key(ID_ESTRUTURA)
);
create table CAIXA_CONEXAO(
 ID_CAIXA_CONEXAO number(4) not null,
 IP number(2) not null,
 DID number(3) not null,
 ESPE_CAB number(2,1) not null,
 COMPRI number (2,1) not null,
 TIP_CONEC varchar2(20) not null,
 primary key (ID_CAIXA_CONEXAO)
);
create table TAMANHO(
 ID_TAMANHO number(4) not null,
 ALT number(4) not null,
 LAR number(4) not null,
 ESPE number(2,1) not null,
 primary key(ID_TAMANHO)
);
create table PLACA(
 ID_PLACA number(4) not null,
 PRECO number(4,2) not null,
 P_MAX number (4) not null,
 T_POTE number (4,2) not null,
 C_POTE number (2,2) not null,
 T_CIRC number (2,2) not null,
 C_CURT number (2,2) not null,
 EFI number (3,2) not null,
 TOLE_POSI number(4) not null,
 TEMP_MIM number(3) not null,
 TEMP_MAX number(3) not null,
 T_MAX number(4) not null,
 CAPA_FUSI number(4) not null,
 NUME_CEL number(4) not null,
 TIP_CEL number(4) not null,
 VID number(4) not null,
 ESTU number(4) not null,
 CAIXA_CONEC number(4) not null,
 TAMA number(4) not null,
 PESO number(3,1) not null,
 IMETRO varchar2 (11),
 foreign key (TIP_CEL) references CELULA(ID_CELULA),
 foreign key (VID) references VIDRO(ID_VIDRO),
 foreign key (ESTU) references ESTRUTURA(ID_ESTRUTURA),
 foreign key (CAIXA_CONEC) references CAIXA_CONEXAO(ID_CAIXA_CONEXAO),
 foreign key (TAMA) references TAMANHO(ID_TAMANHO),
 primary key (ID_PLACA)
);
table cliente
table inderecos
CREATE TABLE ESTADO (
 ID_ESTADO NUMBER(2) PRIMARY KEY NOT NULL,
 NOME_ESTADO VARCHAR2(50) NOT NULL,
 UF CHAR(2) NOT NULL UNIQUE
);
CREATE TABLE CIDADE (
 ID_CIDADE NUMBER(4) PRIMARY KEY NOT NULL,
 NOME_CIDADE VARCHAR2(100) NOT NULL,
 ID_ESTADO NUMBER(2) NOT NULL,
 CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES
ESTADO(ID_ESTADO)
);
CREATE TABLE RUA (
 ID_RUA NUMBER(8) PRIMARY KEY NOT NULL,
 NOME_RUA VARCHAR2(150) NOT NULL,
 ID_CIDADE NUMBER(4) NOT NULL,
 CONSTRAINT FK_RUA_CIDADE FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID_CIDADE)
);
CREATE TABLE ENDERECO_BASE (
 CEP VARCHAR2(8) PRIMARY KEY NOT NULL,
 ID_RUA NUMBER(8) NOT NULL,
 ID_CIDADE NUMBER(4) NOT NULL,
 ID_ESTADO NUMBER(2) NOT NULL,
 CONSTRAINT FK_ENDBASE_RUA FOREIGN KEY (ID_RUA) REFERENCES RUA(ID_RUA),
 CONSTRAINT FK_ENDBASE_CIDADE FOREIGN KEY (ID_CIDADE) REFERENCES
CIDADE(ID_CIDADE),
 CONSTRAINT FK_ENDBASE_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES
ESTADO(ID_ESTADO)
);
table dados cliente
CREATE TABLE CLIENTE(
 CPF_CNPJ VARCHAR2(14) PRIMARY KEY NOT NULL,
 NOME_CLIENTE VARCHAR2(100) NOT NULL,
 DATA_NASCIMENTO DATE NOT NULL
);
CREATE TABLE CLIENTE_ENDERECO (
 ID_CLIENTE_ENDERECO NUMBER(8) PRIMARY KEY NOT NULL,
 CPF_CNPJ_CLIENTE VARCHAR2(14) NOT NULL,
 CEP VARCHAR2(8) NOT NULL,
 NUMERO VARCHAR2(10) NOT NULL,
 COMPLEMENTO VARCHAR2(100),
 CONSTRAINT FK_CLIEND_CLIENTE FOREIGN KEY (CPF_CNPJ_CLIENTE) REFERENCES
CLIENTE(CPF_CNPJ),
 CONSTRAINT FK_CLIEND_ENDBASE FOREIGN KEY (CEP) REFERENCES ENDERECO_BASE(CEP)
);
table instalacao
CREATE TABLE INSTALACAO (
 ID_INSTALACAO NUMBER(8) PRIMARY KEY NOT NULL,
 CPF_CNPJ_CLIENTE VARCHAR2(14) NOT NULL,
 ID_CLIENTE_ENDERECO NUMBER(8) NOT NULL,
 DATA_INSTALACAO DATE,
 DESCRICAO VARCHAR2(200),
 CONSTRAINT FK_INST_CLIENTE FOREIGN KEY (CPF_CNPJ_CLIENTE) REFERENCES
CLIENTE(CPF_CNPJ),
 CONSTRAINT FK_INST_ENDERECO FOREIGN KEY (ID_CLIENTE_ENDERECO) REFERENCES
CLIENTE_ENDERECO(ID_CLIENTE_ENDERECO)
);
CREATE TABLE INSTALACAO_PLACA (
 ID_INSTALACAO NUMBER(8) NOT NULL,
 ID_PLACA NUMBER(4) NOT NULL,
 QUANTIDADE NUMBER(4) NOT NULL,
 CONSTRAINT PK_INSTALACAO_PLACA PRIMARY KEY (ID_INSTALACAO, ID_PLACA),
 CONSTRAINT FK_IP_INSTALACAO FOREIGN KEY (ID_INSTALACAO) REFERENCES
INSTALACAO(ID_INSTALACAO),
 CONSTRAINT FK_IP_PLACA FOREIGN KEY (ID_PLACA) REFERENCES PLACA(ID_PLACA)
);