-- ============================================
-- 🔥 1. APAGA TODAS AS TABELAS (ORDENADAS)
-- ============================================
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CONSUMO;
DROP TABLE IF EXISTS CLIENTE_ENDERECO;
DROP TABLE IF EXISTS RECUPERACAO_SENHA;
DROP TABLE IF EXISTS SIMULACOES;
DROP TABLE IF EXISTS ORCAMENTOS;
DROP TABLE IF EXISTS CONTA;
DROP TABLE IF EXISTS CLIENTE;

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================
-- ⚙️ 2. DESATIVA RESTRIÇÕES TEMPORARIAMENTE
-- ============================================
SET FOREIGN_KEY_CHECKS = 0;

-- ============================================
-- 🧱 3. RECRIAÇÃO DAS TABELAS
-- ============================================


-- Tabela CLIENTE
CREATE TABLE CLIENTE (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    CPF_CNPJ VARCHAR(14) NOT NULL UNIQUE,
    NOME_CLIENTE VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    CLIENTE_INSTALADO TINYINT(1) DEFAULT 0
);

-- Tabela CLIENTE_ENDERECO
CREATE TABLE CLIENTE_ENDERECO (
    ID_CLIENTE_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    CEP VARCHAR(8) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    COMPLEMENTO VARCHAR(100),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

-- Tabela CONTA
CREATE TABLE CONTA (
    ID_CONTA INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA_HASH CHAR(250) NOT NULL,
    TELEFONE VARCHAR(15),
    DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    ULTIMO_LOGIN DATETIME,
    IsAdmin TINYINT(1) DEFAULT 0,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

-- Tabela Recuperação_Senha
CREATE TABLE RECUPERACAO_SENHA (
    ID_RECUPERACAO INT PRIMARY KEY AUTO_INCREMENT,
    ID_CONTA INT NOT NULL,
    TOKEN_HASH VARCHAR(100) NOT NULL,
    DATA_CRIACAO DATETIME NOT NULL,
    DATA_EXPIRACAO DATETIME NOT NULL,
    USADO TINYINT(1) DEFAULT 0,
    FOREIGN KEY (ID_CONTA) REFERENCES CONTA(ID_CONTA)
);

-- Tabela CONSUMO
CREATE TABLE CONSUMO (
    ID_CLIENTE INT NOT NULL,
    ANO INT NOT NULL CHECK (ANO BETWEEN 2000 AND 2100),
    MES INT NOT NULL CHECK (MES BETWEEN 1 AND 12),
    CONSUMO_KWH DECIMAL(6,2) NOT NULL CHECK (CONSUMO_KWH >= 0),
    GERACAO_KWH DECIMAL(6,2) CHECK (GERACAO_KWH >= 0),
    VALOR_TOTAL DECIMAL(8,2) CHECK (VALOR_TOTAL >= 0),
    TIPO_CONSUMO ENUM('RESIDENCIAL', 'COMERCIAL', 'INDUSTRIAL') DEFAULT 'RESIDENCIAL',
    OBSERVACOES VARCHAR(255),
    PRIMARY KEY (ID_CLIENTE, ANO, MES),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

-- Tabela SIMULACOES
CREATE TABLE SIMULACOES (
    ID_SIMULACAO INT PRIMARY KEY AUTO_INCREMENT,
    CONSUMO_MEDIO DECIMAL(8,2) NOT NULL,
    TARIFA_MEDIA DECIMAL(8,4) NOT NULL,
    COBERTURA DECIMAL(5,2) NOT NULL,
    AREA_MINIMA DECIMAL(8,2) NOT NULL,
    VALOR_APROXIMADO DECIMAL(10,2) NOT NULL,
    DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Tabela ORCAMENTOS
CREATE TABLE ORCAMENTOS (
    ID_ORCAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    STATUS ENUM('PENDENTE', 'FINALIZADO') DEFAULT 'PENDENTE',
    DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    DATA_FINALIZACAO DATETIME,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

-- Índices recomendados
CREATE INDEX idx_consumo_cliente_data ON CONSUMO(ID_CLIENTE, ANO, MES);
CREATE INDEX idx_cliente_endereco ON CLIENTE_ENDERECO(ID_CLIENTE);

-- ============================================
-- ✅ REATIVA AS RESTRIÇÕES DE CHAVES ESTRANGEIRAS
-- ============================================
SET FOREIGN_KEY_CHECKS = 1;