-- ============================================
-- 🔥 1. APAGA TODAS AS TABELAS (ORDENADAS)
-- ============================================
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CONSUMO;
DROP TABLE IF EXISTS CONTA;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS CLIENTE_ENDERECO;
DROP TABLE IF EXISTS PLACA;
DROP TABLE IF EXISTS TAMANHO;
DROP TABLE IF EXISTS CAIXA_CONEXAO;
DROP TABLE IF EXISTS ESTRUTURA;
DROP TABLE IF EXISTS VIDRO;
DROP TABLE IF EXISTS CELULA;

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================
-- ⚙️ 2. DESATIVA RESTRIÇÕES TEMPORARIAMENTE
-- ============================================
SET FOREIGN_KEY_CHECKS = 0;

-- ============================================
-- 🧱 3. RECRIAÇÃO DAS TABELAS
-- ============================================

-- Tabela CELULA
CREATE TABLE CELULA (
    ID_CELULA INT PRIMARY KEY AUTO_INCREMENT,
    DSC_CEL VARCHAR(20) NOT NULL
);

-- Tabela VIDRO
CREATE TABLE VIDRO (
    ID_VIDRO INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_VIDRO VARCHAR(20) NOT NULL,
    ESPESSURA DECIMAL(2,1) NOT NULL
);

-- Tabela ESTRUTURA
CREATE TABLE ESTRUTURA (
    ID_ESTRUTURA INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO_ESTRUTURA VARCHAR(50) NOT NULL
);

-- Tabela CAIXA_CONEXAO
CREATE TABLE CAIXA_CONEXAO (
    ID_CAIXA_CONEXAO INT PRIMARY KEY AUTO_INCREMENT,
    IP INT NOT NULL,
    DID INT NOT NULL,
    ESPESSURA_CABO DECIMAL(2,1) NOT NULL,
    COMPRIMENTO DECIMAL(2,1) NOT NULL,
    TIPO_CONEXAO VARCHAR(20) NOT NULL
);

-- Tabela TAMANHO
CREATE TABLE TAMANHO (
    ID_TAMANHO INT PRIMARY KEY AUTO_INCREMENT,
    ALTURA INT NOT NULL,
    LARGURA INT NOT NULL,
    ESPESSURA DECIMAL(2,1) NOT NULL
);

-- Tabela PLACA
CREATE TABLE PLACA (
    ID_PLACA INT PRIMARY KEY AUTO_INCREMENT,
    PRECO DECIMAL(6,2) NOT NULL,
    POTENCIA_MAX INT NOT NULL,
    TENS_POTENCIA DECIMAL(4,2) NOT NULL,
    CORRENTE_POTENCIA DECIMAL(4,2) NOT NULL,
    TENS_CIRC DECIMAL(4,2) NOT NULL,
    CORRENTE_CURTO DECIMAL(4,2) NOT NULL,
    EFICIENCIA DECIMAL(5,2) NOT NULL,
    TOLERANCIA_POSITIVA INT NOT NULL,
    TEMP_MIN INT NOT NULL,
    TEMP_MAX INT NOT NULL,
    TEMP_MAX_SUPORTE INT NOT NULL,
    FUSIVEL INT NOT NULL,
    NUM_CELULAS INT NOT NULL,
    ID_CELULA INT NOT NULL,
    ID_VIDRO INT NOT NULL,
    ID_ESTRUTURA INT NOT NULL,
    ID_CAIXA_CONEXAO INT NOT NULL,
    ID_TAMANHO INT NOT NULL,
    PESO DECIMAL(5,1) NOT NULL,
    IMETRO VARCHAR(11),
    FOREIGN KEY (ID_CELULA) REFERENCES CELULA(ID_CELULA),
    FOREIGN KEY (ID_VIDRO) REFERENCES VIDRO(ID_VIDRO),
    FOREIGN KEY (ID_ESTRUTURA) REFERENCES ESTRUTURA(ID_ESTRUTURA),
    FOREIGN KEY (ID_CAIXA_CONEXAO) REFERENCES CAIXA_CONEXAO(ID_CAIXA_CONEXAO),
    FOREIGN KEY (ID_TAMANHO) REFERENCES TAMANHO(ID_TAMANHO)
);

-- Tabela CLIENTE
CREATE TABLE CLIENTE (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    CPF_CNPJ VARCHAR(14) NOT NULL UNIQUE,
    NOME_CLIENTE VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
);

-- Tabela CLIENTE_ENDERECO
CREATE TABLE CLIENTE_ENDERECO (
    ID_CLIENTE_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    CEP VARCHAR(8) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    COMPLEMENTO VARCHAR(100),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
);

-- Tabela CONTA
CREATE TABLE CONTA (
    ID_CONTA INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA_HASH CHAR(250) NOT NULL,
    TELEFONE VARCHAR(15),
    DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    ULTIMO_LOGIN DATETIME,
    IsAdmin TINYINT(1) DEFAULT 0
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

-- Tabela Recuperação_Senha
CREATE TABLE RECUPERACAO_SENHA (
    ID_RECUPERACAO INT PRIMARY KEY AUTO_INCREMENT,
    ID_CONTA INT NOT NULL,
    TOKEN_HASH VARCHAR(100) NOT NULL,
    DATA_CRIACAO DATETIME NOT NULL,
    DATA_EXPIRACAO DATETIME NOT NULL,
    USADO TINYINT(1) DEFAULT 0,
    FOREIGN KEY (ID_CONTA) REFERENCES CONTA(ID_CONTA)
);

-- Tabela CONSUMO
CREATE TABLE CONSUMO (
    ID_CLIENTE INT NOT NULL,
    ANO INT NOT NULL CHECK (ANO BETWEEN 2000 AND 2100),
    MES INT NOT NULL CHECK (MES BETWEEN 1 AND 12),
    CONSUMO_KWH DECIMAL(6,2) NOT NULL CHECK (CONSUMO_KWH >= 0),
    VALOR_TOTAL DECIMAL(8,2) CHECK (VALOR_TOTAL >= 0),
    TIPO_CONSUMO ENUM('RESIDENCIAL', 'COMERCIAL', 'INDUSTRIAL') DEFAULT 'RESIDENCIAL',
    OBSERVACOES VARCHAR(255),
    PRIMARY KEY (ID_CLIENTE, ANO, MES),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

-- Índices recomendados
CREATE INDEX idx_consumo_cliente_data ON CONSUMO(ID_CLIENTE, ANO, MES);
CREATE INDEX idx_cliente_endereco ON CLIENTE_ENDERECO(ID_CLIENTE);

-- ============================================
-- ✅ REATIVA AS RESTRIÇÕES DE CHAVES ESTRANGEIRAS
-- ============================================
SET FOREIGN_KEY_CHECKS = 1;